spring.batch.job.names: ${job.name:NONE}

spring:
  datasource:
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?characterEncoding=UTF-8&serverTimezone=Asia/Seoul


  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false


